In [4]:
import numpy as np

first_cyclist = np.array([12,33,54,23])
second_cyclist = np.array([32,54,23,53])

total_distance = first_cyclist + second_cyclist

print(total_distance)

[44 87 77 76]


In [5]:
np.add(13,43)

56

In [6]:
np.subtract(23,54)

-31

In [7]:
total_wage = np.array([12,43,22,12,54])*15

In [8]:
print(total_wage)

[180 645 330 180 810]


In [9]:
sum(total_wage)

2145

In [10]:
print(total_wage[total_wage > 300])

[645 330 810]


In [12]:
print(total_wage[total_wage != 330])

[180 645 180 810]


In [13]:
np.logical_and(total_wage > 300, total_wage < 600)

array([False, False,  True, False, False])

In [37]:
#accessing the datas of multiD arrays
cyclist_details = np.array([[12,32,43],[34,23,21]])
print(cyclist_details[0])
print(cyclist_details[1])

[12 32 43]
[34 23 21]


In [38]:
cyclist_details[1][1]

23

In [39]:
first_cycle = cyclist_details[:,1]
first_cycle

array([32, 23])

In [40]:
cyclist_details.ndim

2

In [41]:
cyclist_details.shape

(2, 3)

In [44]:
cyclist_details[:,1:3]

array([[32, 43],
       [23, 21]])

In [45]:
#cyclist_details = np.array([[12,32,43],[34,23,21]])

for i in cyclist_details:
    print(i)

[12 32 43]
[34 23 21]


In [47]:
test_score = np.array([[10,45,14,56],[43,22,56,43]])
passing_score = test_score > 30
passing_score

print(test_score[passing_score])

[45 56 43 56 43]
