In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression


In [31]:
house_data = pd.read_csv('E:\Personal\DataScience\MachineLearning\EncodingSampleDataset.csv')

In [112]:
copy_house_data=house_data
copy_house_data

Town  Area   Price
0      2  2600  565000
1      2  2800  600000
2      2  3200  650000
3      0  3000  580000
4      0  2500  550000
5      2  2600  560000
6      0  2800  590000
7      1  3000  500000
8      1  3200  530000
9      1  3100  510000
10     1  3000  500000
11     1  2600  480000

In [33]:
#Encoding the Town Variable as it is caegorical and ML models work better with numerical data
dummy_data=pd.get_dummies(house_data['Town'])
dummy_data

HBR  Hebbal  Nagwara
0     0       0        1
1     0       0        1
2     0       0        1
3     1       0        0
4     1       0        0
5     0       0        1
6     1       0        0
7     0       1        0
8     0       1        0
9     0       1        0
10    0       1        0
11    0       1        0

In [34]:
house_dummy_data=pd.concat((house_data,dummy_data),axis='columns')

In [35]:
house_dummy_data

Town  Area   Price  HBR  Hebbal  Nagwara
0   Nagwara  2600  565000    0       0        1
1   Nagwara  2800  600000    0       0        1
2   Nagwara  3200  650000    0       0        1
3       HBR  3000  580000    1       0        0
4       HBR  2500  550000    1       0        0
5   Nagwara  2600  560000    0       0        1
6       HBR  2800  590000    1       0        0
7    Hebbal  3000  500000    0       1        0
8    Hebbal  3200  530000    0       1        0
9    Hebbal  3100  510000    0       1        0
10   Hebbal  3000  500000    0       1        0
11   Hebbal  2600  480000    0       1        0

In [36]:
#In this type of one hot enconding we have to drop one encoded column to remove the 
#collinearity or aka data trap
house_dummy_data=house_dummy_data.drop(labels='Nagwara', axis='columns')

In [37]:
house_dummy_data

Town  Area   Price  HBR  Hebbal
0   Nagwara  2600  565000    0       0
1   Nagwara  2800  600000    0       0
2   Nagwara  3200  650000    0       0
3       HBR  3000  580000    1       0
4       HBR  2500  550000    1       0
5   Nagwara  2600  560000    0       0
6       HBR  2800  590000    1       0
7    Hebbal  3000  500000    0       1
8    Hebbal  3200  530000    0       1
9    Hebbal  3100  510000    0       1
10   Hebbal  3000  500000    0       1
11   Hebbal  2600  480000    0       1

In [38]:
X=house_dummy_data[['Area','HBR','Hebbal']] #Taking the independent variables
y=house_dummy_data['Price']  #Dependent/Target variable

In [39]:
house_predict=LinearRegression()

In [40]:
house_predict.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [18]:
house_predict.predict([[3000,1,0]])

array([597180.97447796])

In [41]:
house_predict.score(X,y)

0.9502825744093069

## Applying the same concept using labelEncoder and onehotencoder

In [21]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [99]:
le=LabelEncoder()
ohe=OneHotEncoder(categorical_features=[0]) #this is done to assume the first column as the caegorical feature

In [113]:
copy_house_data

Town  Area   Price
0      2  2600  565000
1      2  2800  600000
2      2  3200  650000
3      0  3000  580000
4      0  2500  550000
5      2  2600  560000
6      0  2800  590000
7      1  3000  500000
8      1  3200  530000
9      1  3100  510000
10     1  3000  500000
11     1  2600  480000

In [88]:
#this step is label encoding
copy_house_data['Town']=le.fit_transform(copy_house_data['Town'])

In [89]:
copy_house_data

Town  Area   Price
0      2  2600  565000
1      2  2800  600000
2      2  3200  650000
3      0  3000  580000
4      0  2500  550000
5      2  2600  560000
6      0  2800  590000
7      1  3000  500000
8      1  3200  530000
9      1  3100  510000
10     1  3000  500000
11     1  2600  480000

In [114]:
X=copy_house_data[['Town','Area']].values
y=copy_house_data['Price']

In [115]:
X

array([[   2, 2600],
       [   2, 2800],
       [   2, 3200],
       [   0, 3000],
       [   0, 2500],
       [   2, 2600],
       [   0, 2800],
       [   1, 3000],
       [   1, 3200],
       [   1, 3100],
       [   1, 3000],
       [   1, 2600]], dtype=int64)

In [116]:
y

0     565000
1     600000
2     650000
3     580000
4     550000
5     560000
6     590000
7     500000
8     530000
9     510000
10    500000
11    480000
Name: Price, dtype: int64

In [117]:
ohe=OneHotEncoder(categorical_features=[0])
ohe

OneHotEncoder(categorical_features=[0], categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [118]:
X=ohe.fit_transform(X).toarray()

C:\Users\vishal.kumar1\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [119]:
X

array([[0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 2.5e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03]])

In [106]:
house_dummy_data

Town  Area   Price  HBR  Hebbal
0   Nagwara  2600  565000    0       0
1   Nagwara  2800  600000    0       0
2   Nagwara  3200  650000    0       0
3       HBR  3000  580000    1       0
4       HBR  2500  550000    1       0
5   Nagwara  2600  560000    0       0
6       HBR  2800  590000    1       0
7    Hebbal  3000  500000    0       1
8    Hebbal  3200  530000    0       1
9    Hebbal  3100  510000    0       1
10   Hebbal  3000  500000    0       1
11   Hebbal  2600  480000    0       1

In [120]:
X=X[:,1:]

In [121]:
X

array([[0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 2.5e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 2.8e+03],
       [1.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 2.6e+03]])

In [122]:
copy_house_model=LinearRegression()

In [123]:
copy_house_model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [125]:
copy_house_model.predict([[0,0,3000]])

array([597180.97447796])