In [13]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

%matplotlib inline

In [5]:
digits_data = load_digits()

In [20]:
data=[0,1,2,3,4,5,6,7,8,9]
kf=KFold(n_splits=3)

In [9]:
kf.get_n_splits([1,2,3,4,5,6,7,8,9])

3

In [21]:
for train_index,test_index in kf.split(data):
    print(train_index,test_index)

[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


In [12]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [14]:
X_train,X_test,y_train,y_test = train_test_split(digits_data.data,digits_data.target,train_size=0.2)

C:\Users\vishal.kumar1\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [15]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

C:\Users\vishal.kumar1\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\vishal.kumar1\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.9325452016689847

In [34]:
LR=[]
svm=[]
rfv=[]

kf=KFold(n_splits=3)

def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)


for train_index,test_index in kf.split(digits_data.data,digits_data.target):
    X_train, X_test = digits_data.data[train_index], digits_data.data[test_index]
    y_train, y_test = digits_data.target[train_index], digits_data.target[test_index]
    LR.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))    
    rfv.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))
    
  

C:\Users\vishal.kumar1\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\vishal.kumar1\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\vishal.kumar1\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\vishal.kumar1\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estim

In [35]:
print('LR Score: ', LR)
print('SVM Score: ', svm)
print('RFV Score: ', rfv)

LR Score:  [0.8964941569282137, 0.9515859766277128, 0.9115191986644408]
SVM Score:  [0.41068447412353926, 0.41569282136894825, 0.4273789649415693]
RFV Score:  [0.8848080133555927, 0.9232053422370617, 0.8948247078464107]


In [41]:
cross_val_score(LogisticRegression(),digits_data.data,digits_data.target,cv=3)

C:\Users\vishal.kumar1\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\vishal.kumar1\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\vishal.kumar1\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\vishal.kumar1\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warn

array([0.89534884, 0.94991653, 0.90939597])

In [43]:
print(cross_val_score(SVC(),digits_data.data,digits_data.target,cv=3))

C:\Users\vishal.kumar1\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\vishal.kumar1\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\vishal.kumar1\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning."

[0.39368771 0.41068447 0.45973154]
