In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [4]:
mails_data=pd.read_csv('E:\Personal\DataScience\MachineLearning\SpamMails.csv',encoding = 'unicode_escape')

In [5]:
mails_data.head()

Category                                            Message Unnamed: 2
0      ham  Go until jurong point, crazy.. Available only ...        NaN
1      ham                      Ok lar... Joking wif u oni...        NaN
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN
3      ham  U dun say so early hor... U c already then say...        NaN
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN

In [6]:
mails_data.drop(columns=['Unnamed: 2'],axis=1,inplace=True)

In [7]:
mails_data.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

The below code is not a good example as it deletes the original data. Hence we should apply the lambda function and add it in a new column and then drop the required column.

In [8]:
mails_data['Category']=mails_data['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [9]:
mails_data.head()

Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

The below command is to rename the columns in a DF if required.

In [11]:
mails_data.rename(columns={'Category': 'Spam Mail'},inplace=True)

Now we will run the process again from the begining.

In [12]:
df_mails=pd.read_csv('E:\Personal\DataScience\MachineLearning\SpamMails.csv',encoding = 'unicode_escape')

In [13]:
df_mails.head()

Category                                            Message Unnamed: 2
0      ham  Go until jurong point, crazy.. Available only ...        NaN
1      ham                      Ok lar... Joking wif u oni...        NaN
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN
3      ham  U dun say so early hor... U c already then say...        NaN
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN

In [15]:
df_mails.drop(columns=['Unnamed: 2'],axis=1,inplace=True)

KeyError: "['Unnamed: 2'] not found in axis"

The above error is coming due to the fact that the column was already dropped

In [16]:
df_mails['SpamMail']=df_mails['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [17]:
df_mails.head()

Category                                            Message  SpamMail
0      ham  Go until jurong point, crazy.. Available only ...         0
1      ham                      Ok lar... Joking wif u oni...         0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...         1
3      ham  U dun say so early hor... U c already then say...         0
4      ham  Nah I don't think he goes to usf, he lives aro...         0

In [18]:
df_mails.drop('Category',axis=1,inplace=True)

In [19]:
df_mails.head()

Message  SpamMail
0  Go until jurong point, crazy.. Available only ...         0
1                      Ok lar... Joking wif u oni...         0
2  Free entry in 2 a wkly comp to win FA Cup fina...         1
3  U dun say so early hor... U c already then say...         0
4  Nah I don't think he goes to usf, he lives aro...         0

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
vector=CountVectorizer()

In [21]:
X_vector=vector.fit_transform(df_mails['Message'])

In [37]:
X_vector.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [38]:
X_vector.toarray().shape

(5574, 8700)

In [26]:
vector.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07090298926',
 '07099833605',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808',
 '07808247860',
 '07808726822',
 '07815296484',
 '07821230901',
 '078498',
 '07880867867',
 '0789xxxxxxx',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '083',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08450542832',
 '084

In [34]:
vector.vocabulary_

{'go': 3563,
 'until': 8072,
 'jurong': 4365,
 'point': 5947,
 'crazy': 2332,
 'available': 1311,
 'only': 5561,
 'in': 4105,
 'bugis': 1761,
 'great': 3646,
 'world': 8536,
 'la': 4491,
 'buffet': 1759,
 'cine': 2055,
 'there': 7682,
 'got': 3607,
 'amore': 1077,
 'wat': 8312,
 'ok': 5528,
 'lar': 4527,
 'joking': 4333,
 'wif': 8438,
 'oni': 5557,
 'free': 3366,
 'entry': 2957,
 'wkly': 8494,
 'comp': 2172,
 'to': 7794,
 'win': 8451,
 'fa': 3094,
 'cup': 2392,
 'final': 3214,
 'tkts': 7781,
 '21st': 410,
 'may': 4949,
 '2005': 401,
 'text': 7633,
 '87121': 790,
 'receive': 6329,
 'question': 6221,
 'std': 7268,
 'txt': 7974,
 'rate': 6273,
 'apply': 1164,
 '08452810075over18': 77,
 'dun': 2809,
 'say': 6668,
 'so': 7063,
 'early': 2830,
 'hor': 3943,
 'already': 1049,
 'then': 7676,
 'nah': 5260,
 'don': 2718,
 'think': 7697,
 'he': 3796,
 'goes': 3571,
 'usf': 8118,
 'lives': 4682,
 'around': 1215,
 'here': 3847,
 'though': 7717,
 'freemsg': 3373,
 'hey': 3857,
 'darling': 2449,
 'it

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_vector,df_mails['SpamMail'],test_size=0.2)

In [28]:
email=df_mails[:2]

In [29]:
email

Message  SpamMail
0  Go until jurong point, crazy.. Available only ...         0
1                      Ok lar... Joking wif u oni...         0

In [30]:
from sklearn.naive_bayes import MultinomialNB

model_spam=MultinomialNB()

In [31]:
model_spam.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [33]:
model_spam.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [40]:
model_spam.score(X_test,y_test)

0.9856502242152466

In [75]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [76]:
vector.transform(emails)

<2x8700 sparse matrix of type '<class 'numpy.int64'>'
	with 22 stored elements in Compressed Sparse Row format>

In [77]:
model_spam.predict(vector.transform(emails))

array([0, 1], dtype=int64)

In [42]:
df_m_data=pd.read_csv('E:\Personal\DataScience\MachineLearning\SpamMails.csv',encoding = 'unicode_escape')

In [45]:
df_m_data.groupby('Category').count()

Message  Unnamed: 2
Category                                                               
ham                                                    4825           0
ham     HI BABE UAWAKE?FEELLIKW SHIT.JUSTFOUND ...        1           1
ham     Yeah                                              1           0
spam                                                    747           0

In [47]:
df_m_data.drop('Unnamed: 2',axis=1, inplace=True)

In [48]:
df_m_data.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [54]:
df_m_data.groupby('Category').describe()

Message         \
                                                     count unique   
Category                                                            
ham                                                   4825   4516   
ham     HI BABE UAWAKE?FEELLIKW SHIT.JUSTFOUND ...       1      1   
ham     Yeah                                             1      1   
spam                                                   747    640   

                                                                                                       \
                                                                                                  top   
Category                                                                                                
ham                                                                            Sorry, I'll call later   
ham     HI BABE UAWAKE?FEELLIKW SHIT.JUSTFOUND ...                                DEVIOUSBITCH.ANYWAY   
ham     Yeah                                                    give me a call if you've got a minute   
spam                                                Please call our customer service representativ...   

                                                         
                                                   freq  
Category                                                 
ham                                                  30  
ham     HI BABE UAWAKE?FEELLIKW SHIT.JUSTFOUND ...    1  
ham     Yeah                                          1  
spam                                                  4

We will be using pipeline method here so that CountVectorizer and multinomialNB are fitted in one step

In [78]:
from sklearn.pipeline import Pipeline

In [85]:
pip_model=Pipeline([('vectorize',CountVectorizer()),('nb',MultinomialNB())])

In [86]:
X_train,X_test,y_train,y_test=train_test_split(df_mails['Message'],df_mails['SpamMail'],test_size=0.2)

In [87]:
pip_model.fit(X_train,y_train)

Pipeline(memory=None,
     steps=[('vectorize', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)), ('nb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [88]:
pip_model.predict(emails)

array([0, 1], dtype=int64)

In [89]:
pip_model.score(X_test,y_test)

0.9847533632286996