In [1]:
import numpy as np

original_dataset = np.array([1,2,3,4])

original_dataset

array([1, 2, 3, 4])

In [2]:
assigned_dataset = original_dataset
assigned_dataset

array([1, 2, 3, 4])

In [3]:
view_dataset = original_dataset.view()
view_dataset

array([1, 2, 3, 4])

In [5]:
view_dataset[2] = 5
view_dataset
#original_dataset

array([1, 2, 5, 4])

In [6]:
copied_dataset = original_dataset.copy()
print(copied_dataset)

copied_dataset[2] = 7
print(copied_dataset)
print(original_dataset)

[1 2 5 4]
[1 2 7 4]
[1 2 5 4]


In [15]:
First_data = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print("First Data : ", First_data)

flattened_data = First_data.ravel()
print("Flattened data : ", flatened_data)

First_data.reshape(2,5)

print("First Data: ", First_data)

First_data.resize(2,5)

print("First Data: ", First_data)

print(np.hsplit(flattened_data,5))

print(np.hstack(flattened_data))

First Data :  [[1 2 3 4 5]
 [6 7 8 9 0]]
Flattened data :  [1 2 3 4 5 6 7 8 9 0]
First Data:  [[1 2 3 4 5]
 [6 7 8 9 0]]
First Data:  [[1 2 3 4 5]
 [6 7 8 9 0]]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9, 0])]
[1 2 3 4 5 6 7 8 9 0]
